# Generated by Django 4.1.7 on 2026-02-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialgoal',
            name='target_date',
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='monthly_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='timeline_months',
            field=models.PositiveIntegerField(default=1, help_text='How many months to complete this goal'),
            preserve_default=False,
        ),
    ]
