# Generated by Django 5.2.11 on 2026-02-26 09:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_financialgoal_target_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialgoal',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='financialgoal',
            name='timeline_months',
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='expected_annual_return',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected annual return %', max_digits=5),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='monthly_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
