# Generated by Django 5.2.11 on 2026-03-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='parent', max_length=20),
        ),
    ]
