# Generated by Django 5.2.11 on 2026-03-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_alter_allocationhistory_category_childprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='children.expensecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='parent_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
