# Generated by Django 5.2.11 on 2026-03-11 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_fundrequest_category_fundrequest_parent_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('action', models.CharField(choices=[('added', 'Allowance Added'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='children.expensecategory')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_history', to='children.childprofile')),
            ],
        ),
    ]
